export type ExampleId =
  | 'ai-generated-code'
  | 'data-analysis'
  | 'interactive-dev'
  | 'ci-testing'
  | 'security-untrusted';

export type SessionId =
  | 'fundamentals'
  | 'executing-code'
  | 'data-workflows'
  | 'preview-workflows'
  | 'automation-ci';

export type ExampleDefinition = {
  id: ExampleId;
  slug: string;
  title: string;
  workshopGoal: string;
  prompt: string;
  defaultInput: string;
  method: 'GET' | 'POST';
};

export type SessionDefinition = {
  id: SessionId;
  slug: string;
  title: string;
  focus: string;
  demo: string;
  handsOn: string;
  useCases?: string[];
  includesTerminal?: boolean;
};

export const sessions: SessionDefinition[] = [
  {
    id: 'fundamentals',
    slug: '/sessions/fundamentals',
    title: 'Session 1: Sandbox Fundamentals',
    focus:
      'What sandboxes solve, how they differ from VMs/serverless, and running a first command.',
    demo: 'Execute a simple shell command and inspect output.',
    handsOn: 'Launch a live PTY terminal connected to a sandbox session.',
    useCases: [
      'Bootstrapping isolated environments for onboarding demos',
      'Running one-off shell diagnostics without touching host machines',
      'Teaching container filesystem and process basics safely'
    ],
    includesTerminal: true
  },
  {
    id: 'executing-code',
    slug: '/sessions/executing-code',
    title: 'Session 2: Executing Code Safely',
    focus: 'Run Node.js and Python scripts and inspect stdout/stderr/exit codes.',
    demo: 'Write and execute short scripts in a sandbox.',
    handsOn: 'Run script execution endpoint and inspect structured output.',
    useCases: [
      'Evaluating AI-generated snippets before production adoption',
      'Running user-submitted code in a controlled boundary',
      'Validating script behavior with deterministic runtime output'
    ]
  },
  {
    id: 'data-workflows',
    slug: '/sessions/data-workflows',
    title: 'Session 3: Data and Analysis Workflows',
    focus: 'Load datasets, transform them, and return computed results.',
    demo: 'Analyze CSV data inside a sandbox.',
    handsOn: 'Run data analysis endpoint and inspect summary metrics.',
    useCases: [
      'Ad hoc analytics on uploaded CSV files',
      'Generating charts and reading artifacts back from sandbox files',
      'Pairing Workers AI code generation with bounded execution'
    ]
  },
  {
    id: 'preview-workflows',
    slug: '/sessions/preview-workflows',
    title: 'Session 4: Interactive and Preview-Based Workflows',
    focus: 'Start HTTP services in sandbox containers and expose preview URLs.',
    demo: 'Run a local preview app in a sandbox.',
    handsOn: 'Launch preview endpoint and open the generated URL.',
    useCases: [
      'Ephemeral app previews for pull requests',
      'Tooling UIs hosted inside per-task sandboxes',
      'Developer workflows that need clickable service URLs'
    ]
  },
  {
    id: 'automation-ci',
    slug: '/sessions/automation-ci',
    title: 'Session 5: Automation and CI Patterns',
    focus: 'Run isolated tests/builds and stream logs for automation flows.',
    demo: 'Execute a test workflow in an isolated environment.',
    handsOn: 'Run CI endpoint and inspect pass/fail output.',
    useCases: [
      'Per-commit test execution in clean environments',
      'Secure build pipelines for untrusted repositories',
      'Background automation jobs with auditable logs'
    ]
  }
];

export const examples: ExampleDefinition[] = [
  {
    id: 'ai-generated-code',
    slug: '/examples/ai-generated-code',
    title: '1. AI-Generated Code Execution',
    workshopGoal: 'Safely run model-generated Python and inspect rich outputs.',
    prompt: 'Paste Python code generated by an AI assistant.',
    defaultInput: `numbers = [4, 8, 15, 16, 23, 42]
print("count:", len(numbers))
print("sum:", sum(numbers))
print("mean:", sum(numbers) / len(numbers))`,
    method: 'POST'
  },
  {
    id: 'data-analysis',
    slug: '/examples/data-analysis',
    title: '2. Data Analysis Workflow',
    workshopGoal: 'Upload CSV data, generate analysis code with AI, and execute it in sandbox.',
    prompt: 'Provide CSV data plus a natural-language analysis question.',
    defaultInput: `region,quarter,revenue,users,channel
us-east,Q1,1200,34,enterprise
us-east,Q2,1390,37,enterprise
us-west,Q1,980,27,self-serve
us-west,Q2,1110,29,self-serve
eu-central,Q1,1430,42,enterprise
eu-central,Q2,1510,44,enterprise
apac,Q1,870,24,self-serve
apac,Q2,990,26,self-serve`,
    method: 'POST'
  },
  {
    id: 'interactive-dev',
    slug: '/examples/interactive-dev',
    title: '3. Interactive Dev Environment',
    workshopGoal: 'Start an HTTP server in a sandbox and open a preview URL.',
    prompt: 'No input needed. This launches a preview app inside the sandbox.',
    defaultInput: '',
    method: 'GET'
  },
  {
    id: 'ci-testing',
    slug: '/examples/ci-testing',
    title: '4. CI, Testing, and Build Pipelines',
    workshopGoal: 'Run JavaScript tests in isolation and capture logs and exit codes.',
    prompt: 'No input needed. This creates a tiny JS project and runs node test.',
    defaultInput: '',
    method: 'POST'
  },
  {
    id: 'security-untrusted',
    slug: '/examples/security-untrusted',
    title: '5. Security and Untrusted Code',
    workshopGoal: 'Execute intentionally risky code in containment and observe behavior.',
    prompt: 'Paste untrusted Python code to run with a short timeout.',
    defaultInput: `import os
print("cwd:", os.getcwd())
print("root entries:", len(os.listdir("/")))
# Sandbox isolates this execution from host infrastructure.`,
    method: 'POST'
  }
];

export const exampleById = Object.fromEntries(
  examples.map((example) => [example.id, example])
) as Record<ExampleId, ExampleDefinition>;

export const sessionById = Object.fromEntries(
  sessions.map((session) => [session.id, session])
) as Record<SessionId, SessionDefinition>;
