export type ExampleId =
  | 'ai-generated-code'
  | 'data-analysis'
  | 'interactive-dev'
  | 'ci-testing'
  | 'security-untrusted';

export type ExampleDefinition = {
  id: ExampleId;
  slug: string;
  title: string;
  workshopGoal: string;
  prompt: string;
  defaultInput: string;
  method: 'GET' | 'POST';
  messages?: {
    successSummary?: string;
    failureSummary?: string;
  };
};

export const examples: ExampleDefinition[] = [
  {
    id: 'ai-generated-code',
    slug: '/examples/ai-generated-code',
    title: '1. AI-Generated Code Execution',
    workshopGoal: 'Safely run model-generated Python and inspect rich outputs.',
    prompt: 'Paste Python code generated by an AI assistant.',
    defaultInput: `numbers = [4, 8, 15, 16, 23, 42]
print("count:", len(numbers))
print("sum:", sum(numbers))
print("mean:", sum(numbers) / len(numbers))`,
    method: 'POST',
    messages: {
      successSummary: 'Code executed in isolated context.',
      failureSummary: 'Code execution returned an interpreter error.'
    }
  },
  {
    id: 'data-analysis',
    slug: '/examples/data-analysis',
    title: '2. Data Analysis Workflow',
    workshopGoal: 'Upload CSV data, generate analysis code with AI, and execute it in sandbox.',
    prompt: 'Provide CSV data plus a natural-language analysis question.',
    defaultInput: `region,quarter,revenue,users,channel
us-east,Q1,1200,34,enterprise
us-east,Q2,1390,37,enterprise
us-west,Q1,980,27,self-serve
us-west,Q2,1110,29,self-serve
eu-central,Q1,1430,42,enterprise
eu-central,Q2,1510,44,enterprise
apac,Q1,870,24,self-serve
apac,Q2,990,26,self-serve`,
    method: 'POST',
    messages: {
      failureSummary: 'AI-generated analysis failed. Review stderr output.'
    }
  },
  {
    id: 'interactive-dev',
    slug: '/examples/interactive-dev',
    title: '3. Interactive Dev Environment',
    workshopGoal: 'Start an HTTP server in a sandbox and open a preview URL.',
    prompt: 'No input needed. This launches a preview app inside the sandbox.',
    defaultInput: '',
    method: 'GET',
    messages: {
      successSummary: 'Preview server started in sandbox and exposed through URL.'
    }
  },
  {
    id: 'ci-testing',
    slug: '/examples/ci-testing',
    title: '4. CI, Testing, and Build Pipelines',
    workshopGoal: 'Run JavaScript tests in isolation and capture logs and exit codes.',
    prompt: 'No input needed. This creates a tiny JS project and runs node test.',
    defaultInput: '',
    method: 'POST',
    messages: {
      successSummary: 'Tests passed in an isolated sandbox.',
      failureSummary: 'Test run failed in sandbox.'
    }
  },
  {
    id: 'security-untrusted',
    slug: '/examples/security-untrusted',
    title: '5. Security and Untrusted Code',
    workshopGoal: 'Execute intentionally risky code in containment and observe behavior.',
    prompt: 'Paste untrusted Python code to run with a short timeout.',
    defaultInput: `import os
print("cwd:", os.getcwd())
print("root entries:", len(os.listdir("/")))
# Sandbox isolates this execution from host infrastructure.`,
    method: 'POST',
    messages: {
      successSummary: 'Untrusted code executed inside sandbox boundary with timeout controls.'
    }
  }
];

export const exampleById = Object.fromEntries(
  examples.map((example) => [example.id, example])
) as Record<ExampleId, ExampleDefinition>;
